### ISSUE TITLE
Some classes with same method names/parameters not clear!

### ISSUE THREAD

**Issue by tpmabb** [CloudRail/cloudrail-si-java-sdk#12]
`webEngine.getLoadWorker().stateProperty().addListener(new ChangeListener<State>() {

                        @Override
                        public void changed(ObservableValue<? extends State> observable, State oldValue,
                                            State newValue) {
                            synchronized (ret) {
                                if (webEngine.getLocation().contains("code=")) {
                                    ret.set(webEngine.getLocation());
                                    stage.close();
                                    ret.notify();
                                }
                            }
                        }

                    });`

Which "state"? As in which class since there are multiple ones?

**Comment by PatrickStoklasa** [comment]
Hi there,

These are just state parameters passed to the change listener for the WebEngine. We are not controlling them but also not using them. So you are free to ignore them or is there a specific reason why you want to use them?
