### ISSUE TITLE
Any idea about Spring-social?

### ISSUE THREAD

**Issue by yangboz** [CloudRail/cloudrail-si-java-sdk#2]
Any idea about Spring-Social: http://projects.spring.io/spring-social ?

**Comment by FlorianWendel** [comment]
I'm not familiar with Spring in particular but it seems to do a similar thing as we do but for Spring only. Do you have any specific question about or suggestion for CloudRail SI?

**Comment by PatrickStoklasa** [comment]
Closed due to inactivity.
