### ISSUE TITLE
Oauth code

### ISSUE THREAD

**Issue by techscientist** [CloudRail/cloudrail-si-java-sdk#6]
Hi,

Nice library! Can you add like a way for us to access the actual oauth code/token etc, via the profile interface when logging in, so that we can use it to authenticate the user on our server, which is Django with the all-auth package?

Thank you.

**Comment by PatrickStoklasa** [comment]
There is way to do this already. Check out the Persistence section in our wiki: https://github.com/CloudRail/cloudrail-si-java-sdk/wiki/Usage#persistence. The method saveAsString() returns a stringified JSON object which contains stuff like access token, refresh token and expiration time.

**Comment by PatrickStoklasa** [comment]
Closed due to inactivity
