### ISSUE TITLE
Persistent not stored for Box

### ISSUE THREAD

**Issue by dbaxley** [CloudRail/cloudrail-si-java-sdk#7]
I use the CloudServices class from the example project to access Google Drive, Box, OneDrive and Dropbox. 

Whenever I specify Box as the storage type, I get a prompt for authorization on first use as well as every use thereafter.

All of the other cloud storage services only prompt for authorization once (on first use).

In my onPause method, I call CloudServices.getInstance().storePersistent(); to make sure that persistent data is stored.

**Comment by PatrickStoklasa** [comment]
Thanks for mentioning it! I will see if i can reproduce the issue and let you know as soon as i have an update.

**Comment by dbaxley** [comment]
I found the problem. I was re-initializing the interface (CloudServices.getInstance().prepare(this);) on each onResume(). Persistence was overlayed each time. Problem solved.
