### ISSUE TITLE
Is it possible to not automatically authenticate on startup?

### ISSUE THREAD

**Issue by gigaSproule** [CloudRail/cloudrail-si-java-sdk#9]
I'm trying to create an application that allows the user a choice of which providers to authenticate with. Is it possible to not automatically try and authenticate on startup?

**Comment by PatrickStoklasa** [comment]
The library should not authenticate on startup anyway. If that is actually the case for you, that would be a bug. The library should only start the authentication process as soon as the first call is made to our library. If you want to control when exactly the authentication process is triggered, you can use the login method. When a user selects one of the providers where he wants to authenticate, just call the login method on that service and it will trigger the authentication process for that particular service.

**Comment by gigaSproule** [comment]
Yes, you are correct. Sorry, I had a stray bit of code that shouldn't have been called.
